---

- name: Ensure modules loaded on boot
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      # k8s modules
      br_netfilter
      overlay
    mode: '0644'

- name: Ensure modules loaded
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay

- name: Ensure sysctl set
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

- name: Ensure zram is stopped
  ansible.builtin.systemd:
    name: systemd-zram-setup@zram0
    state: stopped

- name: Ensure zram is disabled
  ansible.builtin.file:
    path: /etc/systemd/zram-generator.conf
    access_time: preserve
    modification_time: preserve
    state: touch
    mode: '0644'

- name: Install k8s packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - containernetworking-plugins
    - helm
    - kubernetes1.34
    - kubernetes1.34-client
    - kubernetes1.34-kubeadm

- name: Ensure /opt/cni directory exists
  ansible.builtin.file:
    path: /opt/cni
    state: directory
    mode: '0755'

- name: Create symbolic link from /usr/libexec/cni to /opt/cni/bin
  ansible.builtin.file:
    src: /usr/libexec/cni
    dest: /opt/cni/bin
    state: link
    force: true

- name: Enable and start kubelet
  ansible.builtin.systemd:
    name: kubelet
    enabled: true
    daemon_reload: true

- name: Check if firewalld service exists
  ansible.builtin.stat:
    path: /usr/lib/systemd/system/firewalld.service
  register: firewalld_service

- name: Check firewalld status
  ansible.builtin.systemd:
    name: firewalld
  register: firewalld_status
  when: firewalld_service.stat.exists
  ignore_errors: true

- name: Disable and stop firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false
    daemon_reload: true
  when:
    - firewalld_service.stat.exists
    - firewalld_status.status is defined
