---

- name: Ensure systemd-networkd is installed
  ansible.builtin.dnf:
    name:
      - systemd-networkd
      - systemd-resolved
    state: present

- name: Ensure systemd-network directory exists
  ansible.builtin.file:
    path: /etc/systemd/network
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Configure network interfaces
  ansible.builtin.template:
    src: "{{ item.interface_type }}.{{ item.config_type }}.j2"
    dest: "/etc/systemd/network/{{ item.order }}-{{ item.interface_type }}-{{ item.interface_name }}.{{ item.config_type }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ systemd_networkd_interfaces }}"
  loop_control:
    label: "{{ item.order }}-{{ item.interface_type }}-{{ item.interface_name }}.{{ item.config_type }}"
  notify: Restart systemd-networkd

- name: Enable and start systemd-networkd service
  ansible.builtin.systemd:
    name: systemd-networkd
    state: started
    enabled: true
