---

# Enable nested virtualization support for KVM
hypervisor_prepare_enable_nested_virtualization: true

prepare_interface_name: "{{ systemd_networkd_interfaces[0].interface_name }}"

qemu_emulator: '/usr/bin/qemu-kvm'

systemd_networkd_interfaces:
  - interface_name: 'enp1s0'
    interface_type: 'dhcp'
    config_type: 'network'
    order: '10'

  - interface_name: 'vm1'
    interface_type: 'bridge'
    config_type: 'netdev'
    order: '20'

  - interface_name: 'vm1'
    interface_type: 'bridge'
    config_type: 'network'
    order: '25'
    ipv4_address: '10.100.102.2'
    ipv4_prefix: '24'
    ipv4_forward: false

  - interface_name: 'enp2s0'
    interface_type: 'bridge-member'
    config_type: 'network'
    bridge_name: 'vm1'
    order: '30'

hypervisor_ssh_keys: "{{ vault_hypervisor_ssh_keys }}"
cloudinit_root_password_hash: "{{ vault_root_password_hash }}"

hypervisor_networks:
  - name: 'vm1'
    interface_name: 'vm1'
    address: '10.100.102.2'
    netmask: '255.255.255.0'
    gateway: '10.100.102.1'
    domain_name: '102.cofront.xyz'
    dns_servers:
      - '10.100.102.1'

hypervisor_machines: {}