---

# Enable nested virtualization support for KVM
hypervisor_prepare_enable_nested_virtualization: true

prepare_interface_name: "{{ systemd_networkd_interfaces[0].interface_name }}"

qemu_emulator: '/usr/bin/qemu-kvm'

systemd_networkd_interfaces:
  - interface_name: 'enp1s0'
    interface_type: 'dhcp'
    config_type: 'network'
    order: '10'

  - interface_name: 'vm1'
    interface_type: 'bridge'
    config_type: 'netdev'
    order: '20'

  - interface_name: 'vm1'
    interface_type: 'bridge'
    config_type: 'network'
    order: '25'
    ipv4_address: '10.100.102.2'
    ipv4_prefix: '24'
    ipv4_forward: false

  - interface_name: 'enp2s0'
    interface_type: 'bridge-member'
    config_type: 'network'
    bridge_name: 'vm1'
    order: '30'

hypervisor_ssh_keys: "{{ vault_hypervisor_ssh_keys }}"
cloudinit_root_password_hash: "{{ vault_root_password_hash }}"

hypervisor_networks:
  - name: 'vm1'
    interface_name: 'vm1'
    address: '10.100.102.2'
    netmask: '255.255.255.0'
    gateway: '10.100.102.1'
    domain_name: '102.cofront.xyz'
    dns_servers:
      - '10.100.102.1'

base_vm: &base_vm
  cpu_mode: 'host-passthrough'
  image_template: 'fedora-42-cloud'
  boot_disk_size_gb: '20'
  data_disks: []
  memory_gib: '4'
  vcpus: '2'
  gateway: '10.100.102.1'
  dns_servers:
    - '10.100.102.1'
  network_source: 'vm1'
  network_type: 'bridge'

hypervisor_machines:
  vm-101:
    <<: *base_vm
    name: 'vm-101'
    fqdn: 'vm-101.102.cofront.xyz'
    ip: '10.100.102.101/24'
  vm-102:

    <<: *base_vm

    name: 'vm-102'

    fqdn: 'vm-102.102.cofront.xyz'

    ip: '10.100.102.102/24' 
  vm-103:

    <<: *base_vm

    name: 'vm-103'

    fqdn: 'vm-103.102.cofront.xyz'

    ip: '10.100.102.103/24' 
  vm-104:

    <<: *base_vm

    name: 'vm-104'

    fqdn: 'vm-104.102.cofront.xyz'

    ip: '10.100.102.104/24' 
  vm-105:

    <<: *base_vm

    name: 'vm-105'

    fqdn: 'vm-105.102.cofront.xyz'

    ip: '10.100.102.105/24' 
  vm-106:

    <<: *base_vm

    name: 'vm-106'

    fqdn: 'vm-106.102.cofront.xyz'

    ip: '10.100.102.106/24' 
  vm-107:

    <<: *base_vm

    name: 'vm-107'

    fqdn: 'vm-107.102.cofront.xyz'

    ip: '10.100.102.107/24' 
  vm-108:

    <<: *base_vm

    name: 'vm-108'

    fqdn: 'vm-108.102.cofront.xyz'

    ip: '10.100.102.108/24' 
  vm-109:

    <<: *base_vm

    name: 'vm-109'

    fqdn: 'vm-109.102.cofront.xyz'

    ip: '10.100.102.109/24' 
  vm-110:

    <<: *base_vm

    name: 'vm-110'

    fqdn: 'vm-110.102.cofront.xyz'

    ip: '10.100.102.110/24' 
  vm-111:

    <<: *base_vm

    name: 'vm-111'

    fqdn: 'vm-111.102.cofront.xyz'

    ip: '10.100.102.111/24' 
  vm-112:

    <<: *base_vm

    name: 'vm-112'

    fqdn: 'vm-112.102.cofront.xyz'

    ip: '10.100.102.112/24' 
  vm-113:

    <<: *base_vm

    name: 'vm-113'

    fqdn: 'vm-113.102.cofront.xyz'

    ip: '10.100.102.113/24' 
  vm-114:

    <<: *base_vm

    name: 'vm-114'

    fqdn: 'vm-114.102.cofront.xyz'

    ip: '10.100.102.114/24' 
  vm-115:

    <<: *base_vm

    name: 'vm-115'

    fqdn: 'vm-115.102.cofront.xyz'

    ip: '10.100.102.115/24' 
  vm-116:

    <<: *base_vm

    name: 'vm-116'

    fqdn: 'vm-116.102.cofront.xyz'

    ip: '10.100.102.116/24' 
  vm-117:

    <<: *base_vm

    name: 'vm-117'

    fqdn: 'vm-117.102.cofront.xyz'

    ip: '10.100.102.117/24' 
  vm-118:

    <<: *base_vm

    name: 'vm-118'

    fqdn: 'vm-118.102.cofront.xyz'

    ip: '10.100.102.118/24' 
  vm-119:

    <<: *base_vm

    name: 'vm-119'

    fqdn: 'vm-119.102.cofront.xyz'

    ip: '10.100.102.119/24' 
  vm-120:

    <<: *base_vm

    name: 'vm-120'

    fqdn: 'vm-120.102.cofront.xyz'

    ip: '10.100.102.120/24' 
  vm-121:

    <<: *base_vm

    name: 'vm-121'

    fqdn: 'vm-121.102.cofront.xyz'

    ip: '10.100.102.121/24' 
  vm-122:

    <<: *base_vm

    name: 'vm-122'

    fqdn: 'vm-122.102.cofront.xyz'

    ip: '10.100.102.122/24' 
  vm-123:

    <<: *base_vm

    name: 'vm-123'

    fqdn: 'vm-123.102.cofront.xyz'

    ip: '10.100.102.123/24' 
  vm-124:

    <<: *base_vm

    name: 'vm-124'

    fqdn: 'vm-124.102.cofront.xyz'

    ip: '10.100.102.124/24' 
  vm-125:

    <<: *base_vm

    name: 'vm-125'

    fqdn: 'vm-125.102.cofront.xyz'

    ip: '10.100.102.125/24'