---

# Enable nested virtualization support for KVM
hypervisor_prepare_enable_nested_virtualization: true

# BIRD BGP Configuration
bird_bgp_local_asn: 65009
bird_bgp_neighbor_ip: 192.168.254.1
bird_bgp_neighbor_asn: 65001
bird_bgp_multihop: true

systemd_networkd_interfaces:
  - interface_name: 'bond0'
    interface_type: 'bond'
    config_type: 'netdev'
    order: '10'
    mac_address: '3c:ec:ef:43:1c:6e'
  - interface_name: 'bond0'
    interface_type: 'bond'
    config_type: 'link'
    order: '10'
  - interface_name: 'bond0'
    interface_type: 'dhcp'
    config_type: 'network'
    order: '20'
  - interface_name: 'eno1'
    interface_type: 'bond-member'
    bond_name: 'bond0'
    primary_slave: 'true'
    config_type: 'network'
    order: '30'
  - interface_name: 'eno3'
    interface_type: 'bond-member'
    bond_name: 'bond0'
    config_type: 'network'
    order: '30'
  - interface_name: 'br254'
    interface_type: 'bridge'
    config_type: 'netdev'
    order: '40'
  - interface_name: 'br254'
    interface_type: 'bridge'
    config_type: 'network'
    order: '45'
    ipv4_address: '10.254.254.2'
    ipv4_prefix: '24'
    ipv4_forward: false
  - interface_name: 'eno4'
    interface_type: 'bridge-member'
    bridge_name: 'br254'
    config_type: 'network'
    order: '50'

# VM configuration (unified format)
hypervisor_machines:
  bootstrap:
    name: 'bootstrap'
    fqdn: 'bootstrap.cofront.xyz'
    ip: '10.254.254.100/24'
    gateway: '10.254.254.1'
    dns_servers:
      - '8.8.8.8'
      - '1.1.1.1'
    network_source: 'br254'
    network_type: 'bridge'
    ssh_keys: "{{ vault_hypervisor_ssh_keys }}"
    cpu_mode: 'host-passthrough'
    image_template: 'scos-okd'
    boot_disk_size_gb: 120
    memory_gib: 16
    vcpus: 4
    data_disks: []
    skip_cloudinit: true
    fw_cfg_name: 'opt/com.coreos/config'
    fw_cfg_file: '/var/lib/libvirt/images/merged-bootstrap.ign'
  master-1:
    name: 'master-1'
    fqdn: 'master-1.cofront.xyz'
    ip: '10.254.254.101/24'
    gateway: '10.254.254.1'
    dns_servers:
      - '8.8.8.8'
      - '1.1.1.1'
    network_source: 'br254'
    network_type: 'bridge'
    ssh_keys: "{{ vault_hypervisor_ssh_keys }}"
    cpu_mode: 'host-passthrough'
    image_template: 'scos-okd'
    boot_disk_size_gb: 120
    memory_gib: 16
    vcpus: 4
    data_disks: []
    skip_cloudinit: true
    fw_cfg_name: 'opt/com.coreos/config'
    fw_cfg_file: '/var/lib/libvirt/images/merged-master.ign'
  master-2:
    name: 'master-2'
    fqdn: 'master-2.cofront.xyz'
    ip: '10.254.254.102/24'
    gateway: '10.254.254.1'
    dns_servers:
      - '8.8.8.8'
      - '1.1.1.1'
    network_source: 'br254'
    network_type: 'bridge'
    ssh_keys: "{{ vault_hypervisor_ssh_keys }}"
    cpu_mode: 'host-passthrough'
    image_template: 'scos-okd'
    boot_disk_size_gb: 120
    memory_gib: 16
    vcpus: 4
    data_disks: []
    skip_cloudinit: true
    fw_cfg_name: 'opt/com.coreos/config'
    fw_cfg_file: '/var/lib/libvirt/images/merged-master.ign'
  master-3:
    name: 'master-3'
    fqdn: 'master-3.cofront.xyz'
    ip: '10.254.254.103/24'
    gateway: '10.254.254.1'
    dns_servers:
      - '8.8.8.8'
      - '1.1.1.1'
    network_source: 'br254'
    network_type: 'bridge'
    ssh_keys: "{{ vault_hypervisor_ssh_keys }}"
    cpu_mode: 'host-passthrough'
    image_template: 'scos-okd'
    boot_disk_size_gb: 120
    memory_gib: 16
    vcpus: 4
    data_disks: []
    skip_cloudinit: true
    fw_cfg_name: 'opt/com.coreos/config'
    fw_cfg_file: '/var/lib/libvirt/images/merged-master.ign'
