---

# Enable nested virtualization support for KVM
hypervisor_prepare_enable_nested_virtualization: true

# BIRD BGP Configuration
bird_bgp_local_asn: 65009
bird_bgp_neighbor_ip: 192.168.254.1
bird_bgp_neighbor_asn: 65001
bird_bgp_multihop: true

systemd_networkd_interfaces:
  # Bond0 device configuration
  - interface_name: 'bond0'
    interface_type: 'bond'
    config_type: 'netdev'
    order: '10'
    mac_address: '3c:ec:ef:43:1c:6e'
  - interface_name: 'bond0'
    interface_type: 'bond'
    config_type: 'link'
    order: '10'
  - interface_name: 'bond0'
    interface_type: 'dhcp'
    config_type: 'network'
    order: '15'

  # Bond0 members
  - interface_name: 'eno1'
    interface_type: 'bond-member'
    bond_name: 'bond0'
    primary_slave: 'true'
    config_type: 'network'
    order: '20'
  - interface_name: 'eno3'
    interface_type: 'bond-member'
    bond_name: 'bond0'
    config_type: 'network'
    order: '20'

  # Physical interface eno4 with VLAN declarations
  - interface_name: 'eno4'
    interface_type: 'dhcp'
    config_type: 'network'
    order: '30'
    vlans:
      - 'vlan254'
      - 'vlan255'

  # Bridge br254 with VLAN 254
  - interface_name: 'br254'
    interface_type: 'bridge'
    config_type: 'netdev'
    order: '40'
  - interface_name: 'vlan254'
    interface_type: 'vlan'
    config_type: 'netdev'
    order: '45'
    vlan_id: 254
  - interface_name: 'vlan254'
    interface_type: 'vlan'
    config_type: 'network'
    order: '50'
    parent_interface: 'eno4'
    bridge_name: 'br254'
  - interface_name: 'br254'
    interface_type: 'bridge'
    config_type: 'network'
    order: '55'
    ipv4_address: '10.254.254.2'
    ipv4_prefix: '24'
    ipv4_forward: false

  # Bridge br255 with VLAN 255
  - interface_name: 'br255'
    interface_type: 'bridge'
    config_type: 'netdev'
    order: '60'
  - interface_name: 'vlan255'
    interface_type: 'vlan'
    config_type: 'netdev'
    order: '65'
    vlan_id: 255
  - interface_name: 'vlan255'
    interface_type: 'vlan'
    config_type: 'network'
    order: '70'
    parent_interface: 'eno4'
    bridge_name: 'br255'
  - interface_name: 'br255'
    interface_type: 'bridge'
    config_type: 'network'
    order: '75'
    ipv4_address: '10.255.255.2'
    ipv4_prefix: '24'
    ipv4_forward: false

# VM configuration (unified format)
hypervisor_machines:
  bootstrap:
    name: 'bootstrap'
    fqdn: 'bootstrap.cofront.xyz'
    network_interfaces:
      - ip: '10.254.254.100/24'
        gateway: '10.254.254.1'
        dns_servers:
          - '8.8.8.8'
          - '1.1.1.1'
        network_source: 'br254'
        network_type: 'bridge'
        default_route: true
    ssh_keys: "{{ vault_hypervisor_ssh_keys }}"
    cpu_mode: 'host-passthrough'
    image_template: 'scos-okd'
    boot_disk_size_gb: 120
    memory_gib: 16
    vcpus: 4
    data_disks: []
    skip_cloudinit: true
    fw_cfg_name: 'opt/com.coreos/config'
    fw_cfg_file: '/var/lib/libvirt/images/merged-bootstrap.ign'
  master-1:
    name: 'master-1'
    fqdn: 'master-1.dev-1.cofront.xyz'
    network_interfaces:
      - ip: '10.254.254.101/24'
        gateway: '10.254.254.1'
        dns_servers:
          - '8.8.8.8'
          - '1.1.1.1'
        network_source: 'br254'
        network_type: 'bridge'
        default_route: true
    ssh_keys: "{{ vault_hypervisor_ssh_keys }}"
    cpu_mode: 'host-passthrough'
    image_path: '/var/lib/libvirt/images/fedora-43.qcow2'
    image_format: 'qcow2'
    boot_disk_size_gb: 120
    memory_gib: 32
    vcpus: 8
    data_disks: []
    vnc_port: 5901
    vnc_listen: '0.0.0.0'
  master-2:
    # Old ISO-based configuration (for OKD testing):
    # use_empty_boot_disk: true
    # skip_cloudinit: true
    # install_iso_path: '/var/lib/libvirt/images/okd-1.iso'
    name: 'master-2'
    fqdn: 'master-2.dev-1.cofront.xyz'
    network_interfaces:
      - ip: '10.254.254.102/24'
        gateway: '10.254.254.1'
        dns_servers:
          - '8.8.8.8'
          - '1.1.1.1'
        network_source: 'br254'
        network_type: 'bridge'
        default_route: true
    ssh_keys: "{{ vault_hypervisor_ssh_keys }}"
    cpu_mode: 'host-passthrough'
    image_path: '/var/lib/libvirt/images/fedora-43.qcow2'
    image_format: 'qcow2'
    boot_disk_size_gb: 120
    memory_gib: 32
    vcpus: 8
    data_disks: []
    vnc_port: 5902
    vnc_listen: '0.0.0.0'
  master-3:
    # Old ISO-based configuration (for OKD testing):
    # use_empty_boot_disk: true
    # skip_cloudinit: true
    # install_iso_path: '/var/lib/libvirt/images/okd-1.iso'
    name: 'master-3'
    fqdn: 'master-3.dev-1.cofront.xyz'
    network_interfaces:
      - ip: '10.254.254.103/24'
        gateway: '10.254.254.1'
        dns_servers:
          - '8.8.8.8'
          - '1.1.1.1'
        network_source: 'br254'
        network_type: 'bridge'
        default_route: true
    ssh_keys: "{{ vault_hypervisor_ssh_keys }}"
    cpu_mode: 'host-passthrough'
    image_path: '/var/lib/libvirt/images/fedora-43.qcow2'
    image_format: 'qcow2'
    boot_disk_size_gb: 120
    memory_gib: 32
    vcpus: 8
    data_disks: []
    vnc_port: 5903
    vnc_listen: '0.0.0.0'
  tinkerbell:
    name: 'tinkerbell'
    fqdn: 'tinkerbell.cofront.xyz'
    network_interfaces:
      - ip: '10.254.254.10/24'
        gateway: '10.254.254.1'
        dns_servers:
          - '8.8.8.8'
          - '1.1.1.1'
        network_source: 'br254'
        network_type: 'bridge'
        default_route: true
    ssh_keys: "{{ vault_hypervisor_ssh_keys }}"
    cpu_mode: 'host-passthrough'
    image_path: '/var/lib/libvirt/images/fedora-43.qcow2'
    image_format: 'qcow2'
    boot_disk_size_gb: 120
    memory_gib: 8
    vcpus: 4
    data_disks: []
    console_autologin: true
  node-1:
    name: 'node-1'
    fqdn: 'node-1.dev-2.cofront.xyz'
    network_interfaces:
      - ip: '10.255.255.101/24'
        gateway: '10.255.255.1'
        dns_servers:
          - '8.8.8.8'
          - '1.1.1.1'
        network_source: 'br255'
        network_type: 'bridge'
        default_route: true
    ssh_keys: "{{ vault_hypervisor_ssh_keys }}"
    cpu_mode: 'host-passthrough'
    image_path: '/var/lib/libvirt/images/fedora-43.qcow2'
    image_format: 'qcow2'
    boot_disk_size_gb: 120
    memory_gib: 4
    vcpus: 2
    data_disks: []
    console_autologin: true
