---

# Enable nested virtualization support for KVM
hypervisor_prepare_enable_nested_virtualization: true

# BIRD BGP Configuration
bird_bgp_local_asn: 65009
bird_bgp_neighbor_ip: 192.168.254.1
bird_bgp_neighbor_asn: 65001
bird_bgp_multihop: true

systemd_networkd_interfaces:
  - interface_name: 'bond0'
    interface_type: 'bond'
    config_type: 'netdev'
    order: '10'
    mac_address: '3c:ec:ef:43:1c:6e'
  - interface_name: 'bond0'
    interface_type: 'bond'
    config_type: 'link'
    order: '10'
  - interface_name: 'bond0'
    interface_type: 'dhcp'
    config_type: 'network'
    order: '20'
  - interface_name: 'eno1'
    interface_type: 'bond-member'
    bond_name: 'bond0'
    primary_slave: 'true'
    config_type: 'network'
    order: '30'
  - interface_name: 'eno3'
    interface_type: 'bond-member'
    bond_name: 'bond0'
    config_type: 'network'
    order: '30'

# VM configuration (unified format)
hypervisor_machines:
  test-vm:
    name: 'test-vm'
    fqdn: 'test-vm.cofront.xyz'
    ip: '10.55.22.22/32'
    gateway: '169.254.0.1'
    dns_servers:
      - '8.8.8.8'
      - '1.1.1.1'
    ssh_keys: "{{ vault_hypervisor_ssh_keys }}"
    cpu_mode: 'host-passthrough'
    image_template: 'fedora-42-cloud'
    boot_disk_size_gb: 20
    memory_gib: 2
    vcpus: 2
    data_disks: []
