---
- name: List VMs for hypervisor
  hosts: hypervisor
  gather_facts: false
  tasks:
    - name: Fail if more than one host is targeted
      ansible.builtin.fail:
        msg: "You must limit the playbook to a single host using --limit"
      when: ansible_play_hosts | length != 1
    - name: Show VMs defined in inventory
      ansible.builtin.debug:
        msg: "VMs defined for {{ inventory_hostname }}: {{ hypervisor_config.machines.keys() | list }}"
    - name: Show running VMs on host
      community.libvirt.virt:
        command: list_vms
      register: running_vms
    - name: Show running VMs
      ansible.builtin.debug:
        var: running_vms.list_vms
