---
- name: List VMs for hypervisor
  hosts: hypervisor
  become: true
  gather_facts: false
  tasks:
    - name: Fail if more than one host is targeted
      ansible.builtin.fail:
        msg: "You must limit the playbook to a single host using --limit"
      when: ansible_play_hosts | length != 1
    - name: Collect all defined VMs
      ansible.builtin.set_fact:
        all_vms: "{{ hypervisor_machines.keys() | list if hypervisor_machines is defined else [] }}"

    - name: Show VMs defined in inventory
      ansible.builtin.debug:
        msg: "VMs: {{ all_vms }}"
      when: all_vms | length > 0

    - name: Show total defined VMs
      ansible.builtin.debug:
        msg: "Total VMs defined for {{ inventory_hostname }}: {{ all_vms | length }}"

    - name: Show running VMs on host
      community.libvirt.virt:
        command: list_vms
      register: running_vms
    - name: Show running VMs
      ansible.builtin.debug:
        var: running_vms.list_vms
