- name: Remove unused packages
  ansible.builtin.dnf:
    name:
      - abrt
      - at
      - avahi
      - avahi-libs
      - cronie
      - gssproxy
    state: absent
    autoremove: true
    allowerasing: true

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - systemd-networkd
      - systemd-resolved

- name: Ensure systemd-network directory exists
  ansible.builtin.file:
    path: /etc/systemd/network
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Configure default network interface with DHCP
  ansible.builtin.template:
    src: interface.network.j2
    dest: "/etc/systemd/network/10-{{ prepare_interface_name }}.network"
    owner: root
    group: root
    mode: '0644'
  notify: Prepare Reboot

- name: Disable NetworkManager
  ansible.builtin.systemd_service:
    name: NetworkManager
    enabled: false
  failed_when: false  # Do not fail even if disabling fails

- name: Enable systemd-networkd
  ansible.builtin.systemd_service:
    name: systemd-networkd
    enabled: true

- name: Flush Handlers (to apply network changes immediately)
  ansible.builtin.meta: flush_handlers

- name: Remove NetworkManager packages
  ansible.builtin.dnf:
    name:
      - NetworkManager
    state: absent
    autoremove: true
    allowerasing: true
