- name: Remove unused packages
  ansible.builtin.dnf:
    name:
      - abrt
      - at
      - avahi
      - avahi-libs
      - cronie
      - gssproxy
    state: absent
    autoremove: true
    allowerasing: true

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - systemd-networkd
      - systemd-resolved

- name: Disable NetworkManager
  ansible.builtin.systemd_service:
    name: NetworkManager
    enabled: false
    state: stopped
  failed_when: false  # Do not fail even if disabling fails

- name: Setup systemd-networkd
  ansible.builtin.include_role:
    name: systemd-networkd

- name: Remove NetworkManager packages
  ansible.builtin.dnf:
    name:
      - NetworkManager
    state: absent
    autoremove: true
    allowerasing: true
