---

- name: Install Packages
  ansible.builtin.package:
    name: "{{ libvirt_packages }}"
    state: present

- name: Enable and start libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: true

- name: Remove default network
  community.libvirt.virt_net:
    name: default
    command: undefine
    state: absent
