---

libvirt_packages:
  - bridge-utils
  - genisoimage
  - libvirt-client
  - libvirt-daemon-driver-qemu
  - libvirt-daemon-kvm
  - python3-libvirt
  - python3-lxml
  - python3-json-logger
  - python3-pyroute2
  - qemu-kvm
