---

- name: Create zot user
  ansible.builtin.user:
    name: zot
    system: true
    shell: /bin/false
    home: "{{ zot_home_dir }}"
    create_home: false

- name: Create base zot directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: zot
    group: zot
    mode: '0755'
  loop:
    - "{{ zot_home_dir }}"
    - "{{ zot_data_dir }}"
    - "{{ zot_config_dir }}"

- name: Create registry subdirectories
  ansible.builtin.file:
    path: "{{ zot_data_dir }}{{ item.path }}"
    state: directory
    owner: zot
    group: zot
    mode: '0755'
  loop: "{{ zot_registries }}"

- name: Download zot binary with checksum verification
  ansible.builtin.get_url:
    url: "https://github.com/project-zot/zot/releases/download/v{{ zot_version }}/{{ zot_binary_name }}"
    dest: "{{ zot_binary_dest }}/{{ zot_binary_final_name }}"
    mode: '0755'
    owner: root
    group: root
    checksum: "sha256:https://github.com/project-zot/zot/releases/download/v{{ zot_version }}/checksums.sha256.txt"
    backup: true

- name: Deploy zot configuration
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ zot_config_dir }}/config.yaml"
    owner: zot
    group: zot
    mode: '0644'
  notify: restart zot

- name: Deploy zot systemd unit file
  ansible.builtin.template:
    src: zot.service.j2
    dest: /etc/systemd/system/zot.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart zot

- name: Start and enable zot service
  ansible.builtin.systemd:
    name: zot
    state: started
    enabled: true
    daemon_reload: true
