apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: peer-65001
spec:
  timers:
    holdTimeSeconds: 90
    keepAliveTimeSeconds: 30
  ebgpMultihop: 10
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
  - afi: ipv4
    safi: unicast
    advertisements:
      matchLabels:
        advertise: "bgp"
