---
# Simple test VM for LoadBalancer static IP
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-vm
  namespace: default
spec:
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: t3.small
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
    spec:
      architecture: amd64
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            name: default
        firmware:
          uuid: 1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d
        machine:
          type: q35
        resources: {}
      networks:
      - name: default
        pod: {}
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo
        name: containerdisk
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            password: kubevirt
            chpasswd: { expire: False }
            ssh_pwauth: True
        name: cloudinitdisk