---

- name: Install FRR package
  ansible.builtin.dnf:
    name: frr
    state: present

- name: Ensure FRR configuration directory exists
  ansible.builtin.file:
    path: /etc/frr
    state: directory
    mode: '0755'
    owner: frr
    group: frr

- name: Configure FRR daemons
  ansible.builtin.template:
    src: daemons.j2
    dest: /etc/frr/daemons
    owner: frr
    group: frr
    mode: '0640'
  notify: Restart frr

- name: Configure FRR main configuration
  ansible.builtin.template:
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    owner: frr
    group: frr
    mode: '0640'
    validate: /usr/bin/vtysh -C -f %s
  notify: Reload frr

- name: Enable and start FRR service
  ansible.builtin.systemd:
    name: frr
    state: started
    enabled: true
