---

systemd_networkd_interfaces:
  - interface_name: 'bond0'
    interface_type: 'bond'
    config_type: 'netdev'
    order: '10'
    mac_address: '3c:ec:ef:43:1c:6e'
  - interface_name: 'bond0'
    interface_type: 'bond'
    config_type: 'link'
    order: '10'
  - interface_name: 'bond0'
    interface_type: 'dhcp'
    config_type: 'network'
    order: '20'
  - interface_name: 'eno1'
    interface_type: 'bond-member'
    bond_name: 'bond0'
    primary_slave: 'true'
    config_type: 'network'
    order: '30'
  - interface_name: 'eno3'
    interface_type: 'bond-member'
    bond_name: 'bond0'
    config_type: 'network'
    order: '30'

  - interface_name: 'vm1'
    interface_type: 'bridge'
    config_type: 'netdev'
    order: '20'

  - interface_name: 'vm1'
    interface_type: 'bridge'
    config_type: 'network'
    order: '25'

  - interface_name: 'eno4'
    interface_type: 'bridge-member'
    config_type: 'network'
    bridge_name: 'vm1'
    order: '30'
