---
- name: Initial System Preparation
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Fail if more than one host is targeted
      ansible.builtin.fail:
        msg: "You must limit the playbook to a single host using --limit"
      when: ansible_play_hosts | length != 1
    - name: Run prepare role
      ansible.builtin.include_role:
        name: system_prepare
    - name: Reboot server
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
    - name: Verify server is responsive after reboot
      ansible.builtin.ping:
